config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'users/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resource :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true
	validates :description, presence: true

	belongs_to :user
	has_many :comments
	has_many_attached :pictures
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	
	has_many :posts
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit::Authorization
	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

	private

	def user_not_authorized
		flash[:notice] = "You are not authorized."
		redirect_to(request.referrer || root_path)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:update, :new, :create, :edit]
  before_action :find_comment, only: [:update, :show, :edit, :destroy]

  def show
  end

  def new
    @comment = @post.comments.new
  end

  def create
    if @post.comments.create(comment_params)
      redirect_to @post, notice: "Comment successfully created"
    else
      render 'new'
    end
  end

  def edit
    authorize @comment
  end

  def update
    if @comment.update(comment_params)
      redirect_to @post, notice: "Comment successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    authorize @comment
    @comment.destroy
   
    redirect_to @post, notice: "Comment successfully deleted"
  end
  
  private 

  def find_comment
    @comment = @post.comments.find(params[:id] || comment_params[:id])
  end

  def comment_params
    params.require(:comment).permit(:id, :message, :post_id,:user_id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def validate_user
    @comment = current_user.comments.find_by(:id => params[:id] || comment_params[:id])
    redirect_to post_path(:id => params[:post_id]), notice: "Not Authorized" if @comment.nil?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :destroy]

  def index
    @current_user_posts = current_user.posts if current_user.present?
    @posts = Post.all
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def edit
    authorize @post
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to @post, notice: "Post successfully created"
    else
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    authorize @post
    @deleted_post= Post.destroy(@post.id)
    if @deleted_post
      redirect_to posts_path
    else
      render 'show'
    end
  end
  
  private 

  def find_post
    @post = Post.find(params[:id])
  end

  def validate_user
    @post = current_user.posts.find_by(:id => params[:id])
    redirect_to posts_path, notice: "Not Authorized" if @post.nil?
  end

  def post_params
    params.require(:post).permit(:title, :description, pictures: [],)
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
   devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<div class="container-fluid w-25 border mt-5 rounded">
  <h4 class="text-center p-2">Add Comment</h4>
  <%= form_for([@post, Comment.new], method: method, local: true) do |form| %>
    <%= form.hidden_field :post_id, value: @post.id %>
    <%= form.hidden_field :id, value: comment.id %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <div class="mb-3">
      <%= form.label :message, class: "form-label" %>
      <%= form.text_field :message, placeholder: 'Comment', value: comment.message, class: "form-control" %>
      <% if comment.errors.any? %>
	    <div class="invalid-feedback d-block">
	      <% comment.errors.full_messages_for(:message).each do |error_message| %>
	        <%= error_message %>.
	      <% end %>
	    </div>
	  <% end %>
    </div>

    <div class="mb-3 text-center">
      <%= form.submit value: button, class: "btn btn-primary toaster-check" %>
    </div>
  <% end %>
</div>

app/views/comments/edit.html.erb
<%= render partial: "form", locals:{:comment => @comment, method: :patch, button: "Update Comment"} %>

app/views/comments/new.html.erb
<%= render partial: "form", locals:{:comment => @comment, method: :post, button: "Create Comment"} %>

app/views/comments/show.html.erb
<div>
    <h1><%= @comment.message %></h1>
    <%= link_to "Delete", post_comment_path(@comment),method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Home", posts_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%if user_signed_in? %>
          <li class="nav-item">
              <%= link_to "New Post", new_post_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_toaster.html.erb
<div class="d-flex border text-bg-warning rounded my-2 py-2 toast">
  <div class="toast-body">
      <%= message %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserPosts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </head>

  <body>
    <div>
      <%= render "layouts/header"%>
      <% if notice %>
        <div class="position-absolute toast-container top-0 end-0 p-5">
          <%= render partial: "layouts/toaster", locals:{:message => notice}%>
        </div>
      <% end %>
    </div>
    <%= yield %><br><br><br>
    <footer class="text-center">Copyright Muneeb © 2022</footer>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container-fluid w-25 border mt-5 rounded">
  <h4 class="text-center p-2">Add Post</h4>
  <%= form_with(model: post, local: true) do |form| %>
    <div class="mb-3">
      <%= form.label :title, class: "form-label" %>
      <%= form.text_field :title, placeholder: 'Post Title', class: "form-control" %>
      <% if post.errors.any? %>
	    <div class="invalid-feedback d-block">
	      <% post.errors.full_messages_for(:title).each do |error_message| %>
	        <%= error_message %>.
	      <% end %>
	    </div>
	  <% end %>
    </div>

    <div class="mb-3">
      <%= form.label :description, class: "form-label" %>
      <%= form.text_area :description, placeholder: 'Post Description', class: "form-control" %>
      <% if post.errors.any? %>
	    <div class="invalid-feedback d-block">
	      <% post.errors.full_messages_for(:description).each do |error_message| %>
	        <%= error_message %>.
	      <% end %>
	    </div>
	  <% end %>
    </div>

    <div class="input-group mb-3">
      <%= form.file_field :pictures, class: "form-control", multiple: true %>
    </div>

    <div class="mb-3 text-center">
      <%= form.submit class: "btn btn-primary toaster-check" %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render partial: "form", locals:{:post => @post} %>

app/views/posts/index.html.erb
<div class="container-fluid">
  	<% if @current_user_posts %>
  		<div class="container-fluid">
		  	<h1 class="text-center">
		    	Your Posts
		  	</h1>
		  	<div class="d-flex m-2 justify-content-center">
			  <% @current_user_posts.each do |post| %>
			  	<div class="card shadow mx-3" style="width: 23rem;">
			  		<%= image_tag post.pictures.first, style:'height:250px;width:100%;object-fit:cover;', class: 'card-img-top border' if post.pictures.any?%>
				  <div class="card-body text-center">
				    <h5 class="card-title"><%= post.title%></h5>
				    <p class="card-text"><%= post.description %><br>Comments: <%= post.comments.count %></p>
				    <%= link_to "Read Post", post, class: "btn btn-primary text-decoration-none" %>
				  </div>
				</div>
			  <% end %>
			</div>
		</div>
  <% end %>
	<div class="container-fluid">
	  <h1 class="text-center">
	    Posts
	  </h1>
	  <div class="d-flex m-2 justify-content-center">
	  	<% @posts.each do |post| %>
	  		<% if current_user %>
	  			<% if post.user_id != current_user.id %>
	  			<div class="card shadow" style="width: 23rem;">
			  		<%= image_tag post.pictures.first,style:'height:250px;width:100%;object-fit:cover;', class: 'card-img-top border' if post.pictures.any?%>
				  <div class="card-body text-center">
				    <h5 class="card-title"><%= post.title%></h5>
				    <p class="card-text"><%= post.description %><br>Comments: <%= post.comments.count %></p>
				    <%= link_to "Read Post", post, class: "btn btn-primary text-decoration-none" %>
				  </div>
				</div>
		  		<% end %>
		  	<% else %>
		  	<div class="card shadow mx-3" style="width: 23rem;">
		  		<%= image_tag post.pictures.first,style:'height:250px;width:100%;object-fit:cover;', class: 'card-img-top border' if post.pictures.any?%>
			  <div class="card-body text-center">
			    <h5 class="card-title"><%= post.title%></h5>
			    <p class="card-text"><%= post.description %><br>Comments: <%= post.comments.count %></p>
			    <%= link_to "Read Post", post, class: "btn btn-primary text-decoration-none" %>
			  </div>
			</div>
	  		<% end %>
	  	<% end %>
		<div>
	</div>
</div>

app/views/posts/new.html.erb
<%= render partial: "form", locals:{:post => @post} %>

app/views/posts/show.html.erb
<%= link_to "", :back, class: 'btn btn-dark carousel-control-prev-icon m-2' %>
<div class="d-flex justify-content-center">
    <div class="card m-3 text-center" style="width: 50rem">

        <% if @post.pictures.any? %>
            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators bg-dark">
                    <% @post.pictures.each_with_index do |picture,index| %>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= index %>" class="<%= "active" if index == 0 %>" aria-current="true"></button>
                    <% end %>
                </div>
              <div class="carousel-inner">
                <% @post.pictures.each_with_index do |picture,index| %>
                    <div class="carousel-item <%= "active" if index == 0 %>">
                      <%= image_tag picture, style: 'height:300px;width:100%;object-fit:cover;' %>
                    </div>
                <% end %>
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon bg-dark" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                <span class="carousel-control-next-icon bg-dark" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
        <% end %>

        <div class="card-body">
            <h5 class="card-title"><%= @post.title %></h5>
            <p class="card-text"><%= @post.description%></p>
        </div>

        <div class="actions">
            <% if user_signed_in? %>
                <% if policy(@post).edit? %>
                    <%= link_to "Delete", post_path(@post),method: :delete, data: {:confirm => "Are you sure"}, class: 'btn btn-danger m-1', style: 'width:fit-content' %>
                    <%= link_to "Edit", edit_post_path, class: 'btn btn-primary', style: 'width:fit-content' %>
                <% end %>
                <%= link_to "Add Comment", new_post_comments_path(:post_id => @post.id), class: 'btn btn-primary', style: 'width:fit-content' %>
            <% end %>
                
        </div>
        <% if !@post.comments.nil? %>
        <ul class="list-group mt-3">
          <% @post.comments.each do |comment| %>
              <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                <%= comment.message %> <%= link_to "Edit", edit_post_comments_path(:id =>comment.id,:post_id => comment.post_id), class: "text-decoration-none" if user_signed_in? && policy(comment).edit? %>
              </li>
          <% end %>
        </ul>
      <% end %>
    </div>
</div>